export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_PENDING = 'LOGOUT_PENDING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

export const TOKEN_REFRESH_PENDING = 'TOKEN_REFRESH_PENDING'
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS'
export const TOKEN_REFRESH_ERROR = 'TOKEN_REFRESH_ERROR'

export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN'
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'

export const USER_PENDING = 'USER_PENDING'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_ERROR = 'USER_ERROR'
export const SET_USER = 'SET_USER'

export const GALLERY_REMOVE_PHOTOS = 'GALLERY_REMOVE_PHOTOS'
export const GALLERY_REMOVE_PENDING = 'GALLERY_REMOVE_PENDING'
export const GALLERY_REMOVE_SUCCESS = 'GALLERY_REMOVE_SUCCESS'
export const GALLERY_REMOVE_ERROR = 'GALLERY_REMOVE_ERROR'
export const GALLERY_ADD_PHOTOS = 'GALLERY_ADD_PHOTOS'
export const GALLERY_ADD_PENDING = 'GALLERY_ADD_PENDING'
export const GALLERY_ADD_SUCCESS = 'GALLERY_ADD_SUCCESS'
export const GALLERY_ADD_ERROR = 'GALLERY_ADD_ERROR'
export const GALLERY_SET_PHOTOS = 'GALLERY_SET_PHOTOS'
export const GALLERY_SET_SELECTION = 'GALLERY_SET_SELECTION'
export const GALLERY_SET_SCROLLABLE = 'GALLERY_SET_SCROLLABLE'

