export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const REGISTER_PENDING = 'REGISTER_PENDING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const TOKEN_PENDING = 'TOKEN_PENDING'
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS'
export const TOKEN_ERROR = 'TOKEN_ERROR'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER = 'SET_USER'

export const TOP_RECIPES_PENDING = 'TOP_RECIPES_PENDING'
export const TOP_RECIPES_SUCCESS = 'TOP_RECIPES_SUCCESS'
export const TOP_RECIPES_ERROR = 'TOP_RECIPES_ERROR'
export const SET_TOP_RECIPES = 'SET_TOP_RECIPES'

export const CATEGORY_RECIPES_PENDING = 'CATEGORY_RECIPES_PENDING'
export const CATEGORY_RECIPES_SUCCESS = 'CATEGORY_RECIPES_SUCCESS'
export const CATEGORY_RECIPES_ERROR = 'CATEGORY_RECIPES_ERROR'
export const SET_CATEGORY_RECIPES = 'SET_CATEGORY_RECIPES'



